cask_args appdir: "/Applications"
tap "homebrew/cask-fonts"
tap "petere/postgresql"
brew "bash"
brew "bash-completion"
brew "git"
brew "mobile-shell"
brew "nodenv"
brew "rbenv"
brew "rbenv-default-gems"
brew "redis", restart_service: :changed
brew "ripgrep"
brew "tmux"
brew "watchman"
brew "yarn"
brew "petere/postgresql/postgresql-common"
cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "firefox"
cask "font-inconsolata-dz-for-powerline"
cask "google-chrome"
cask "imageoptim"
cask "iterm2"
cask "licecap"
cask "macvim"
cask "whatsapp"
