cask_args appdir: "/Applications"
tap "caskroom/cask"
tap "petere/postgresql"
brew "bash"
brew "bash-completion"
brew "git"
brew "mobile-shell"
brew "rbenv"
brew "rbenv-default-gems"
brew "tmux"
brew "vim", args: ["with-custom-ruby"]
brew "watchman"
brew "petere/postgresql/postgresql-common"
brew "petere/postgresql/postgresql@9.6"
cask "1password"
cask "adobe-creative-cloud"
cask "duet"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "licecap"
cask "macvim"
cask "skype"
cask "virtualbox"
cask "whatsapp"
mas "Xcode", id: 497799835
