execute pathogen#infect()

" theme
set background=dark
colorscheme hybrid_material
set guifont=Inconsolata\ for\ Powerline:h12
" hide scrollbars
set guioptions=
" match console line spacing
set linespace=1

" hide buffers without prompt
set hidden

" reduce time to react to change
set updatetime=250

" use two spaces for tabs
set expandtab
set softtabstop=2
set shiftwidth=2

" line numbers
set number
set relativenumber

" highlight current line
set cursorline

" highlight matching bracket
set showmatch

" show invisibles
set list
set listchars=tab:▸\ ,eol:¬,trail:·

" search downwards in the project directory
set path+=**
" highlight previous search matches
set hlsearch
" ignore case in pattern
set ignorecase
" ...if pattern contains only lowercase letters
set smartcase

" <leader> key map
let mapleader=','

" Emacs bindings
imap <C-d> <Del>

" window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

if has('autocmd')
  " highlight characters beyond column 80
  augroup vimrc_autocmds
    autocmd BufEnter * highlight OverLength ctermbg=red ctermfg=white
    autocmd BufEnter,WinEnter * match OverLength /\%>80v.\+/
  augroup END

  " stopwritingramblingcommitmessages.com
  autocmd Filetype gitcommit setlocal spell
endif

" vim-airline statusline
set laststatus=2
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#left_sep=' '
let g:airline#extensions#tabline#left_alt_sep='|'
let g:airline#extensions#tabline#show_buffers=0
let g:airline_powerline_fonts=1
let g:airline_theme='hybrid'
" remove erroneous symbol at end of statusline
let g:airline_skip_empty_sections=1
" angled separators render poorly in console
let g:airline_left_sep=''
let g:airline_right_sep=''

" CtrlP fuzzy file finder
" search only files un/tracked by Git
let g:ctrlp_user_command=['.git', 'git --git-dir=%s/.git ls-files -co --exclude-standard']

" Gundo.vim
nnoremap <F5> :GundoToggle<CR>

" Ale
let g:airline#extensions#ale#enabled = 1
let g:ale_lint_on_text_changed='never'
