export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:$HOME/.rbenv/bin:$PATH"

# editor
if [ -z "$VISUAL" ]; then
	type vim >/dev/null 2>&1 && VISUAL=vim || VISUAL=vi
fi
EDITOR=$VISUAL
export VISUAL EDITOR

# bash-completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
	. $(brew --prefix)/etc/bash_completion
fi

# rbenv: enable shims and autocompletion
eval "$(rbenv init -)"

# prompt
export PS1='\[\e[1;33m\]\w\[\e[0m\]$(__git_ps1 " (%s)")$ '

export PAGER=less

# iCloud Drive directory
export ICLOUD=$HOME/Library/Mobile\ Documents/com~apple~CloudDocs

alias ls='ls -G'
alias artcat="ls /tmp/cover.png | entr -c $HOME/.ncmpcpp/artcat"
